name: 'issue-creator'
description: 'Periodically create GitHub issue'
inputs:
  template-issue:
    description: 'Specify the issue number of the template in the repository. e.g. 1'
    required: true
  close-last-issue:
    description: 'If true, issue-creator closes the previous issue.'
    default: true
  check-before-create-issue:
    description: 'shell script'
    default: "echo 'OK'"
  token:
    default: ${{ github.token }}
  repository:
    description: 'e.g. rerost/issue-creator'
    default: ${{ github.repository }}
runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - issue-creator
    - create
    - https://github.com/${{ inputs.repository }}/issues/${{ inputs.template-issue }}
    - --CloseLastIssue=${{ inputs.close-last-issue }}
    - --check-before-create-issue=${{ inputs.check-before-create-issue }}
    - --GithubAccessToken=${{ inputs.token }}
