name: "Check actions work"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          template-issue-url: https://github.com/rerost/issue-creator/issues/1
