name: "Check actions work"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: .
        with:
          template-issue: 1
